language: android
android:
  components:
    # The BuildTools version used by your project
    - build-tools-25.0.3

    # The SDK version used to compile your project
    - android-25

before_install:
- mkdir "$ANDROID_HOME/licenses" || true
- cp licenses $ANDROID_HOME/licenses
- chmod +x gradlew